version: '3.4'

services:
  rabbitmq:
    hostname: "localhost"
    container_name: "rabbitmq"
    image: rabbitmq:3.8-management-alpine
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    ports:
      - "15672:15672"  # port do RabbitMQ management plugin
      - "5672:5672"    # port do RabbitMQ
